# Generated by Django 3.2.9 on 2022-04-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220428_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='working_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.workinghours'),
        ),
    ]
