# Generated by Django 3.2.9 on 2022-04-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_account_working_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(auto_created=True)),
                ('place', models.CharField(max_length=99)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.browser')),
            ],
        ),
    ]
