# Generated by Django 3.2.9 on 2022-04-30 14:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_browser_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
