# Generated by Django 3.2.9 on 2022-04-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mark_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
