# Generated by Django 3.2.9 on 2022-04-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_mark_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='photo',
        ),
    ]
