# Generated by Django 3.2.9 on 2022-04-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_mark_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='marks',
            field=models.ManyToManyField(blank=True, to='api.Mark'),
        ),
    ]
