# Generated by Django 3.2.9 on 2022-05-02 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_account_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='marks',
            field=models.ManyToManyField(blank=True, to='api.Mark'),
        ),
        migrations.AddField(
            model_name='mark',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
