# Generated by Django 3.2.9 on 2022-05-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220502_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='external_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='redirect_to',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
