# Generated by Django 3.2.9 on 2022-05-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_business_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='us',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
