# Generated by Django 3.2.9 on 2022-05-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_business_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='enrollment',
            field=models.TextField(default=''),
        ),
    ]
