# Generated by Django 3.2.9 on 2022-05-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_account_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='enrollment',
        ),
    ]
